# this example is the default behavior of rpc-perf
# non-ratelimitied hotkey get suitable for memcache or redis on a 1byte key
#
# use-case: benchmark peak throughput for 128b value (hitrate: 100%)

[general]
timeout = 10

[[workload]]
name = "get"
method = "get"
rate = 0
  [[workload.parameter]]
  style = "static"
  size = 1
  seed = 0

[[workload]]
name = "set"
method = "set"
rate = 1
  [[workload.parameter]]
  style = "static"
  size = 1
  seed = 0
  [[workload.parameter]]
  style = "random"
  size = 128
  regenerate = false
