[general]
protocol = "pelikan_rds" # Pelikan RDS (Rich Data Server)
interval = 60 # seconds
windows = 5 # run for 5 intervals
clients = 1 # use a single client thread
poolsize = 1 # each client has 1 connection per endpoint
tcp_nodelay = false # do not enable tcp_nodelay
request_timeout = 200_000 # microseconds
connect_timeout = 200_000 # microseconds

[[keyspace]]
length = 8 # 8 byte keys
count = 10_000_000 # limit to 10M keys
weight = 1 # this keyspace has a weight of 1
commands = [
    {action = "sarray_create", weight = 1, watermark_low = 3000, watermark_high = 3200},
    {action = "sarray_delete", weight = 1},
    {action = "sarray_find", weight = 1},
    {action = "sarray_get", weight = 1},
    {action = "sarray_insert", weight = 1, items = 1},
    {action = "sarray_len", weight = 1},
    {action = "sarray_remove", weight = 1, items = 1},
    {action = "sarray_truncate", weight = 1, items = 128},
]
values = [ # values will be u64 integers
    {length = 8, weight = 1, class = "integer"},
]
