[general]
# specify the protocol to be used
protocol = "ping"
# the interval for stats integration and reporting
interval = 60
# the number of intervals to run the test for
windows = 5
# when service is true, the runtime is unlimited
service = false
# controls the number of worker threads to launch, each worker thread maintains
# its own event loop and connection pool to each endpoint
threads = 4
# run the admin thread with a HTTP listener at the address provided, this allows
# stats exposition via HTTP
admin = "127.0.0.1:9090"

[target]
# specify one or more endpoints as IP:PORT pairs
endpoints = [
	"127.0.0.1:12321"
]

[connection]
# the number of connections to each endpoint from each thread, the total number
# of connections to each endpoint is: poolsize * threads
poolsize = 25

[request]
# set a global ratelimit for requests
ratelimit = 50000

[[keyspace]]
# controls what commands will be used in this keyspace
commands = [
	{ verb = "ping", weight = 1 },
]
