# this example runs a mixed key-value workload with a key/val dataset
# sized to be exactly 500,000 6 byte keys with 64 byte values.
#
# num can be specified with random workloads to generate random keys
# from a precisely sized set of potential keys.
#
# note that size must be sufficiently large to contain the number of
# decimal digits in num.
#
# when unspecified, num will default to 0. in this case, the default
# behavior of random workload will apply, where random ascii strings
# that are of length size are generated.

[general]
request-timeout = 200
connect-timeout = 500

[[workload]]
name = "get"
method = "get"
rate = 40000
  [[workload.parameter]]
  style = "random"
  size = 6
  num = 500000
  regenerate = true

[[workload]]
name = "set"
method = "set"
rate = 10000
  [[workload.parameter]]
  style = "random"
  size = 6
  num = 500000
  regenerate = true
  [[workload.parameter]]
  style = "random"
  size = 64
  regenerate = true
