[package]
name = "rpc-perf"
version = "3.0.0-pre"
authors = ["Brian Martin <bmartin@twitter.com>"]
edition = "2018"
license = "Apache-2.0"
description = "RPC Performance Testing"
homepage = "https://github.com/twitter/rpc-perf"
repository = "https://github.com/twitter/rpc-perf"
readme = "README.md"


[dependencies]
buffer = { path = "../buffer" }
byteorder = "1.2.7"
bytes = "0.4.11"
clap = "2.32.0"
codec = { path = "../codec" }
crc = "1.8.1"
datastructures = { path = "../datastructures" }
getopts = "0.2.18"
logger = { path = "../logger" }
metrics = { path = "../metrics" }
mio = "0.6.16"
mpmc = "0.1.2"
rand = "0.6.1"
ratelimiter = { path = "../ratelimiter" }
rustls = { version = "0.14.0", optional = true }
serde = "1.0.85"
serde_derive = "1.0.85"
slab = "0.4.1"
time = "0.1.42"
timer = { path = "../timer" }
tiny_http = "0.6.2"
toml = "0.4.10"
waterfall = { path = "../waterfall" }
webpki = { version = "0.18.1", optional = true }

[features]
default = []
tls = ["rustls/dangerous_configuration", "webpki"]
