on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  linux:
    name: ubuntu
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Run
      run: bash build/ci.sh
  macos:
    name: macos
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - name: Run
      run: bash build/ci.sh
  rustfmt:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: rustfmt
      run: cargo fmt -- --check
  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: clippy
      run: cargo clippy
  audit:
    name: audit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install
      run: cargo install cargo-audit
    - name: audit
      run: cargo audit --ignore RUSTSEC-2020-0031
  memcache-smoketest:
    name: memcache smoketest
    runs-on: ubuntu-18.04
    services:
      memcached:
        image: memcached
        ports: 
          - 11211:11211        
    steps:
      - uses: actions/checkout@v2
      - name: Run
        run: bash build/ci.sh
      - name: Smoketest
        run: target/release/rpc-perf --config rpc-perf/configs/default.toml --endpoint localhost:11211
  exposition-smoketest:
    name: exposition smoketest
    runs-on: ubuntu-18.04
    services:
      memcached:
        image: memcached
        ports:
          - 11211:11211
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: bash build/ci.sh
      - name: Run
        run: target/release/rpc-perf --config rpc-perf/configs/default.toml --endpoint localhost:11211 --listen 127.0.0.1:9090 &
      - name: Validate
        run: sleep 60 && curl -s http://localhost:8080/vars.json | jq '.' > /dev/null
